CREATE DATABASE doan2
GO	
USE doan2
GO 
CREATE TABLE KHOACHUYENNGANH 
(
ID INT IDENTITY(1,1),
MAKHOA NVARCHAR(10) PRIMARY KEY,
TENKHOA NVARCHAR(50) NOT NULL
)
CREATE TABLE GIAOVIEN
(
ID INT IDENTITY(1,1),
MAGV NVARCHAR(10) PRIMARY KEY,
TAIKHOAN NVARCHAR(20) NOT NULL,
MATKHAU NVARCHAR(20) NOT NULL,
TENGV NVARCHAR(50) NOT NULL,
GIOITINH NVARCHAR(10) NOT NULL,
MAKHOA NVARCHAR(10) NOT NULL,
FOREIGN KEY (MAKHOA) REFERENCES dbo.KHOACHUYENNGANH(MAKHOA)
)
CREATE TABLE KHOA 
(
ID INT IDENTITY(1,1),
MAKHOASV NVARCHAR(10) PRIMARY KEY,
TENKHOASV NVARCHAR(50) NOT NULL,
TINCHIHT INT NOT NULL
)
CREATE TABLE MONHOC
(
ID INT IDENTITY(1,1),
MAMON NVARCHAR(10) PRIMARY KEY,
TENMON NVARCHAR(50) NOT NULL,
TCMON INT NOT NULL,
TIENTC BIGINT NOT NULL,
TONGTIEN BIGINT NOT NULL,
MAKHOA NVARCHAR(10) NOT NULL,
FOREIGN KEY (MAKHOA) REFERENCES dbo.KHOACHUYENNGANH(MAKHOA)
)
CREATE TABLE HOCKYNAMHOC
(
ID INT IDENTITY(1,1),
MAHKNH NVARCHAR(10) PRIMARY KEY,
TENHKNH NVARCHAR(50) NOT NULL
)
CREATE TABLE SINHVIEN
(
ID INT IDENTITY(1,1),
MASV NVARCHAR(10) PRIMARY KEY,
TAIKHOANSV NVARCHAR(30) NOT NULL,
MATKHAUSV VARCHAR(30) NOT NULL,
TENSV NVARCHAR(50) NOT NULL,
GIOITINHSV NVARCHAR(10) NOT NULL,
NAMSINH INT NOT NULL,
MAKHOASV NVARCHAR(10) NOT NULL,
MAKHOA NVARCHAR(10) NOT NULL,
FOREIGN KEY (MAKHOASV) REFERENCES dbo.KHOA (MAKHOASV),
FOREIGN KEY (MAKHOA) REFERENCES dbo.KHOACHUYENNGANH (MAKHOA)
)
CREATE TABLE BANGDIEMHP
(
ID INT IDENTITY(1,1),
MAHP NVARCHAR(10) PRIMARY KEY,
MAMON NVARCHAR(10) NOT NULL,
DIEMQT FLOAT NOT NULL,
DIEMGK FLOAT NOT NULL,
DIEMTHI FLOAT NOT NULL,
DIEMHP FLOAT NOT NULL ,
DIEMCHU NVARCHAR(10) NOT NULL,
HE4 FLOAT NOT NULL,
GHICHU NVARCHAR(20) NOT NULL,
MASV NVARCHAR(10) NOT NULL,
MAHKNH NVARCHAR(10) NOT NULL,
FOREIGN KEY (MASV) REFERENCES dbo.SINHVIEN (MASV),
FOREIGN KEY (MAHKNH) REFERENCES dbo.HOCKYNAMHOC (MAHKNH),
FOREIGN KEY (MAMON) REFERENCES dbo.MONHOC (MAMON)
)
CREATE TABLE MONHOCSV 
(
	MAMONHOCSV NVARCHAR(10) PRIMARY KEY,
	TONGTCHTNH INT NOT NULL,
	TCCONLAI INT NOT NULL,
	MAMON NVARCHAR(10) NOT NULL,
	MAHP NVARCHAR(10) NOT NULL,
	FOREIGN KEY (MAMON) REFERENCES dbo.MONHOC(MAMON),
	FOREIGN KEY (MAHP) REFERENCES dbo.BANGDIEMHP(MAHP)
)


INSERT INTO dbo.KHOACHUYENNGANH
(
    MAKHOA,
    TENKHOA
)
VALUES
(   N'KHOA1', -- MAKHOA - nvarchar(10)
    N'CNTT'  -- TENKHOA - nvarchar(50)
    )

INSERT INTO dbo.KHOA
(
    MAKHOASV,
    TENKHOASV,
    TINCHIHT
)
VALUES
(   N'K43', -- MAKHOASV - nvarchar(10)
    N'CNTT K43', -- TENKHOA - nvarchar(50)
    150    -- TINCHIHT - int
    )

	INSERT INTO dbo.SINHVIEN
	(
	    MASV,
		TAIKHOANSV,
		MATKHAUSV,
	    TENSV,
	    GIOITINHSV,
	    NAMSINH,
	    MAKHOASV,
	    MAKHOA
	)
	VALUES
	(   N'SV1', -- MASV - nvarchar(10)
		N'NHATNAM',
		N'123456',
	    N'MAI NHAT NAM', -- TENSV - nvarchar(50)
	    N'NAM', -- GIOITINHSV - nvarchar(10)
	    2000,   -- NAMSINH - int
	    N'K43', -- MAKHOASV - nvarchar(10)
	    N'KHOA1'  -- MAKHOA - nvarchar(10)
	)
		---------------------------------------------------------------------------
	INSERT INTO dbo.KHOACHUYENNGANH
(
    MAKHOA,
    TENKHOA
)
VALUES
(   N'KHOA2', -- MAKHOA - nvarchar(10)
    N'CNOTO'  -- TENKHOA - nvarchar(50)
    )

INSERT INTO dbo.KHOA
(
    MAKHOASV,
    TENKHOASV,
    TINCHIHT
)
VALUES
(   N'K432', -- MAKHOASV - nvarchar(10)
    N'CNOTO K43', -- TENKHOA - nvarchar(50)
    150    -- TINCHIHT - int
    )

	INSERT INTO dbo.SINHVIEN
	(
	    MASV,
		TAIKHOANSV,
		MATKHAUSV,
	    TENSV,
	    GIOITINHSV,
	    NAMSINH,
	    MAKHOASV,
	    MAKHOA
	)
	VALUES
	(   N'SV2', -- MASV - nvarchar(10)
		N'NHATNAM2',
		N'123456',
	    N'MAI NHAT NAM', -- TENSV - nvarchar(50)
	    N'NAM', -- GIOITINHSV - nvarchar(10)
	    2000,   -- NAMSINH - int
	    N'K432', -- MAKHOASV - nvarchar(10)
	    N'KHOA2'  -- MAKHOA - nvarchar(10)
	)
	INSERT INTO dbo.HOCKYNAMHOC
	(
	    MAHKNH,
	    TENHKNH
	)
	VALUES
	(   N'1', -- MAHKNH - nvarchar(10)
	    N'hk1 - 2018-2019'  -- TENHKNH - nvarchar(50)
	    )
	INSERT INTO dbo.MONHOC
	(
	    MAMON,
	    TENMON,
	    TCMON,
	    TIENTC,
	    TONGTIEN,
	    MAKHOA
	)
	VALUES
	(   N'1', -- MAMON - nvarchar(10)
	    N'DOTNET', -- TENMON - nvarchar(50)
	    4,   -- TCMON - int
	    350.000,   -- TIENTC - bigint
	    4*350.000,   -- TONGTIEN - bigint
	    N'KHOA1'  -- MAKHOA - nvarchar(10)
	    )

	INSERT INTO dbo.BANGDIEMHP
	(
	    MAHP,
	    MAMON,
	    DIEMQT,
	    DIEMGK,
	    DIEMTHI,
	    DIEMHP,
	    DIEMCHU,
	    HE4,
	    GHICHU,
	    MASV,
	    MAHKNH
	)
	VALUES
	(   N'1', -- MAHP - nvarchar(10)
	    N'1', -- MAMON - nvarchar(10)
	    10, -- DIEMQT - float
	    6.5, -- DIEMGK - float
	    6.5, -- DIEMTHI - float
	    ((10+(6.5*4))+(6.5*5))/10, -- DIEMHP - float
	    N'KHONG', -- DIEMCHU - nvarchar(10)
	    6,   -- HE4 - int
	    N'KHONG', -- GHICHU - nvarchar(20)
	    N'SV1', -- MASV - nvarchar(10)
	    N'1'  -- MAHKNH - nvarchar(10)
	    )

SELECT MASV , TENSV , GIOITINHSV , NAMSINH , TENKHOASV , TENKHOA FROM dbo.SINHVIEN,dbo.KHOACHUYENNGANH , dbo.KHOA 
WHERE dbo.SINHVIEN.MAKHOASV = dbo.KHOA.MAKHOASV AND dbo.SINHVIEN.MAKHOA = dbo.KHOACHUYENNGANH.MAKHOA

SELECT TENSV,TENKHOASV,TENMON ,DIEMQT , DIEMGK , DIEMTHI , DIEMHP , DIEMCHU   FROM dbo.BANGDIEMHP,dbo.MONHOC,dbo.SINHVIEN, dbo.HOCKYNAMHOC,dbo.KHOA
WHERE dbo.BANGDIEMHP.MASV = dbo.SINHVIEN.MASV AND dbo.BANGDIEMHP.MAMON = dbo.MONHOC.MAMON AND dbo.SINHVIEN.MAKHOASV = dbo.KHOA.MAKHOASV

SELECT * FROM dbo.MONHOCSV


INSERT INTO dbo.MONHOCSV
(
    MAMONHOCSV,
    TONGTCHTNH,
    TCCONLAI,
    MAMON,
    MAHP
)
VALUES
(   N'1', -- MAMONHOCSV - nvarchar(10)
    5,   -- TONGTCHTNH - int
    140,   -- TCCONLAI - int
    N'1', -- MAMON - nvarchar(10)
    N'1'  -- MAHP - nvarchar(10)
    )

	----XEM LẠI MONHOCSV-------